trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: GravtCI
  displayName: Terraform CI SG-Gravt
  steps:
    - checkout: self
    - template: ./templates/workspace-ci.yml
      parameters:
        WorkspacePath: ./live
    - template: ./templates/workspace-ci.yml
      parameters:
        WorkspacePath: ./modules
    - template: ./templates/workspace-ci.yml
      parameters:
        WorkspacePath: ./sg-gravt
    - template: ./templates/workspace-ci.yml
      parameters:
        WorkspacePath: ./sg-shared-prod
